Feat/add get tasks list
TanguyChusseau/training-node pull request #1
Opened 2020-09-30 08:49 UTC by TanguyChusseau

2020-09-30 14:06 UTC, jordantaillefer commented on .eslintrc.json
> +    "no-console": "off",
pourquoi ? on ne veut pas de console.log

2020-09-30 14:06 UTC, jordantaillefer commented on .eslintrc.json
> +    "no-unused-vars": "warn",
pourquoi ? On ne veut pas de unused vars donc error !

2020-09-30 14:06 UTC, jordantaillefer commented on .eslintrc.json
> +    "prettier/prettier": [
pourquoi ? Ca devrait être ddans le prettier rc

2020-09-30 14:06 UTC, jordantaillefer commented on .prettierrc.json
> +  "printWidth": 120,
Du coup il manque le endofline ici

2020-09-30 14:06 UTC, jordantaillefer commented on index.js
> +router.delete('/tasks/:id', async (ctx) => {
en entrée on appelle ca plutot request / reply

2020-09-30 14:13 UTC, TanguyChusseau commented on .eslintrc.json
> +    "prettier/prettier": [
En cherchant l'erreur j'avais vu que c'était lié à eslint, c'est juste pour ça !

2020-09-30 14:13 UTC, TanguyChusseau commented on .eslintrc.json
> +    "no-unused-vars": "warn",
Pour éviter que ça devienne relou quand tu dev, un warning suffit je trouve.

2020-09-30 14:13 UTC, TanguyChusseau commented on .eslintrc.json
> +    "no-console": "off",
Woopsie

2020-09-30 14:14 UTC, TanguyChusseau commented on index.js
> +router.delete('/tasks/:id', async (ctx) => {
J'ai vu plusieurs fois le combo oui, et aussi l'approche contexte pour tout, mais ouais c'est plus clair avec req, res I guess

2020-10-01 11:28 UTC, jordantaillefer requested changes

2020-10-01 11:28 UTC, jordantaillefer commented on index.js
> +router.delete('/tasks/:id', async (res) => {
pas besoin de async

2020-10-01 11:28 UTC, jordantaillefer commented on index.js
> +  res.body = tasks
res.body = task.filter(...)

2020-10-01 11:28 UTC, jordantaillefer commented on index.js
> +app.listen(3001)
Le console.log ici est intéressant pour signifier le bon démarrage de l'app

Mais vu que console.log est interdit, on peut utiliser console.info pour montrer que c'est un console log d'information plutot que de debug

Y'aura peut être une modif de la config lint à faire

2020-10-01 13:14 UTC, nathmotion commented on index.js
> +app.listen(3001)
Est ce que tu prefere qu'on change la regle  =>" no-console" : ["error", { allow: ["warn", "error"] }]  https://eslint.org/docs/rules/no-console

Ou  on fasse leve la regle seulement pour la ligne  comme ça :
![image](https://user-images.githubusercontent.com/19632865/94813850-d24d8300-03f8-11eb-83c5-0ca0efa33c50.png)

2020-10-01 13:21 UTC, nathmotion commented on index.js
> +app.listen(3001)
la premier marche pas oublie

2020-10-01 16:00 UTC, jordantaillefer commented on index.js
> +  console.info('Server Started') // eslint-disable-line no-console
Il faut faire en sorte que eslintrc accept tout les console sauf console.log pas disable le linter

2020-10-02 08:57 UTC, nathmotion commented on index.js
> +  console.info('Server Started') // eslint-disable-line no-console
- [ ] done

2020-10-03 10:20 UTC, jordantaillefer approved these changes

2020-10-03 10:20 UTC, merged