Feat/add tests
TanguyChusseau/training-node pull request #4
Opened 2020-11-12 11:34 UTC by nathmotion

Add units tests and integration test , with coverage report

2020-11-19 20:36 UTC, jordantaillefer requested changes

2020-11-19 20:36 UTC, jordantaillefer commented on api/router.ts
> +import { createFactory } from './container'
import container from './container'

2020-11-19 20:36 UTC, jordantaillefer commented on api/tasks/tests/task-controller.test.ts
> +import { createFactory } from '../../container'
import container from './container'

2020-11-19 20:36 UTC, jordantaillefer commented on api/tasks/tests/task-controller.test.ts
> +import { Request } from 'koa'
Pour les imports, il est plus clair d'avoir les imports de lib puis ligne vide puis les imports de projet, genre 

import { Request } from 'koa'
import { StubbedInstance, stubInterface } from 'ts-sinon'

import { CreateTask, INIT_TASKS } from '../domain/task'
import container from '../../container'

2020-11-20 18:55 UTC, nathmotion commented on api/router.ts
> +import { createFactory } from './container'
done

2020-11-20 18:56 UTC, nathmotion commented on api/tasks/tests/task-controller.test.ts
> +import { createFactory } from '../../container'
done

2020-11-20 18:57 UTC, nathmotion commented on api/tasks/tests/task-controller.test.ts
> +import { Request } from 'koa'
done

2020-12-18 12:34 UTC, jordantaillefer approved these changes

2020-12-18 12:34 UTC, merged